<a href="https://colab.research.google.com/github/anjalitiwarics27-coder/aiml/blob/main/4_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
marks=[55,90,40,70,80]
bonus=5
new_marks=[]
for m in marks:
  new_marks.append(m+bonus)
print(new_marks)

[60, 95, 45, 75, 85]


In [ ]:
# numpy--> numerical python

In [2]:
import numpy as np
bonus=10
marks=np.array([55,90,40,70,80])
new_marks=marks+bonus
print(new_marks)

[ 65 100  50  80  90]


In [3]:
a=[4,6,8,2,1]
a[0]

4

In [4]:
a[1]

6

In [5]:
a.append(10)

In [6]:
a

[4, 6, 8, 2, 1, 10]

In [7]:
a=[4,6,8,2,1]
type(a)

list

In [9]:
print(a)

[4, 6, 8, 2, 1]


In [8]:
np_a=np.array(a)
print(np_a)

[4 6 8 2 1]


In [10]:
type(np_a)

numpy.ndarray

In [11]:
# given a python list:
a=[3,6,1,9]
b=[]
for i in a:
  b.append(i*2)
print(b)

[6, 12, 2, 18]


In [13]:
type(np_a)

numpy.ndarray

In [12]:
type(b)

list

In [16]:
a_np=np.array(a)
b_np=a_np*2
print(b_np)

[ 6 12  2 18]


In [17]:
type(b_np)

numpy.ndarray

In [20]:
a_np

array([3, 6, 1, 9])

In [18]:
a_np-2

array([ 1,  4, -1,  7])

In [19]:
a_np+2

array([ 5,  8,  3, 11])

In [21]:
a_np/2

array([1.5, 3. , 0.5, 4.5])

In [22]:
a=[6,12,2,18]
b=np.array(a)

In [24]:
a=[[2,4,5],
   [6,3,1],
   [5,7,2]]
type(a)

list

In [25]:
print(a)

[[2, 4, 5], [6, 3, 1], [5, 7, 2]]


In [26]:
b=np.array(a)
print(b)

[[2 4 5]
 [6 3 1]
 [5 7 2]]


In [27]:
type(b)

numpy.ndarray

In [29]:
a=np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [31]:
a=np.zeros((4,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [32]:
a=np.ones(4)
print(a)

[1. 1. 1. 1.]


In [33]:
a=np.ones((4,5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [36]:
a=np.arange(5)
print(a)

[0 1 2 3 4]


In [37]:
a

array([0, 1, 2, 3, 4])

In [38]:
a=np.arange(1,11)

In [39]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
type(a)

numpy.ndarray

In [41]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [42]:
np.arange(5,11)

array([ 5,  6,  7,  8,  9, 10])

In [43]:
np.arange(1,32)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [44]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
#linespace ky krta h equal values mein divide kr deta hein
# jaise upr ke code mein 0 se 10 tak ke mein 5 bagh mein divide kr raha hein

##Arithmetic Operations

In [45]:
a=np.array([3,5,6])
b=np.array([5,6,1])

In [46]:
print(a)

[3 5 6]


In [47]:
print(a)

[3 5 6]


In [48]:
print(b)

[5 6 1]


In [52]:
a=[3,5,6]
b=[5,6,1]
c=[]
n=len(a)
for i in range(n):
  c.append(a[i]+b[i])
print(c)

[8, 11, 7]


In [53]:
an=np.array(a)
bn=np.array(b)
cn=an+bn
print(cn)

[ 8 11  7]


In [54]:
print(an-bn)

[-2 -1  5]


In [55]:
print(an*bn)

[15 30  6]


In [56]:
print(an)

[3 5 6]


In [57]:
print(an**2)

[ 9 25 36]


In [58]:
print(an+5)

[ 8 10 11]


In [59]:
print(an*5)

[15 25 30]


In [60]:
print(an)

[3 5 6]
