<a href="https://colab.research.google.com/github/anjalitiwarics27-coder/aiml/blob/main/4_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# np.where(condition,True,False)

In [3]:
import numpy as np
marks = np.array([3,5,7,2,1])

In [4]:
marks

array([3, 5, 7, 2, 1])

In [5]:
np.where(marks>5,"yes","no")


array(['no', 'no', 'yes', 'no', 'no'], dtype='<U3')

In [6]:
# Give students this towards the end .
employees = np.array([
    [101,45000,120000],
    [102,60000,180000],
    [103,35000,90000],
    [104,75000,250000],
    [105,50000,160000]
])

In [7]:
# columns:
# employees_id,salary,sales

In [8]:
#employees with sales >= $150,000 receive 5% commision otherwise 2% comission .
# 2. sales > 200000,excellent,150000 --> good , else improvement

In [9]:
employees = np.array([
    [101,45000,120000],
    [102,60000,180000],
    [103,35000,90000],
    [104,75000,250000],
    [105,50000,160000]
])

In [10]:
sales = employees[:,2]

In [11]:
category = np.where(sales >200000,"Excellent",np.where(sales>150000,"Good","Need Improvement"))

In [12]:
print(category)

['Need Improvement' 'Good' 'Need Improvement' 'Excellent' 'Good']


In [13]:
commision = np.where(sales>150000,sales*0.05,sales*0.02)

In [14]:
print(commision)

[ 2400.  9000.  1800. 12500.  8000.]


In [15]:
import numpy as np
sales = np.array([
    120,150,180,200,220,250,270,300,320,350,380,400
])

In [16]:
sales.ndim

1

In [17]:
sales.shape

(12,)

In [18]:
#  4 quarter ---> 3 month each .

In [19]:
qtr_sales= sales.reshape(4,3)
qtr_sales

array([[120, 150, 180],
       [200, 220, 250],
       [270, 300, 320],
       [350, 380, 400]])

In [20]:
qtr_sales.shape

(4, 3)

In [21]:
sales

array([120, 150, 180, 200, 220, 250, 270, 300, 320, 350, 380, 400])

In [22]:
numbers= np.array([1,2,3,4,5,6])
a= numbers.reshape(2,3)
print(a)

[[1 2 3]
 [4 5 6]]


In [23]:
numbers = np.array([1,2,3,4,5,6])
a=numbers.reshape(3,3)
print(a)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [ ]:
marks = np.array([
    72,81,65,90,77,
    88,69,91,73,84,
    60,75,82,79,95,
    68,71,86,89,93
])

In [24]:
# 4*5
# sum of each row

In [29]:
n_m = marks.reshape(4,5)
n_m

ValueError: cannot reshape array of size 5 into shape (4,5)

In [30]:
np.sum(n_m,axis=1)

NameError: name 'n_m' is not defined

In [31]:
marks

array([3, 5, 7, 2, 1])

In [32]:
marks.size

5

In [33]:
n_m= marks.reshape(5,-1)

In [80]:
n_m

array([[3],
       [5],
       [7],
       [2],
       [1]])

In [81]:
a= n_m.reshape(-1,2)
a

ValueError: cannot reshape array of size 5 into shape (2)

In [82]:
b= n_m.reshape(-1,3)

ValueError: cannot reshape array of size 5 into shape (3)

In [83]:
matrix = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

In [84]:
matrix.shape

(3, 3)

In [85]:
a= matrix.flatten()

In [86]:
matrix.shape

(3, 3)

In [87]:
a.shape

(9,)

In [88]:
sales= np.array([
    [100,120,150],
    [90,110,130],
    [200,220,250]
])

In [89]:
# want the average sales for all 9 months

In [90]:
np.mean(sales)

np.float64(152.22222222222223)

In [91]:
np.mean(sales,axis=1)

array([123.33333333, 110.        , 223.33333333])

In [92]:
a = sales.flatten()

In [93]:
np.mean(a)

np.float64(152.22222222222223)

In [94]:
a=np.arange(30)

In [95]:
b= a.reshape(2,5,3)

In [96]:
b=a.reshape(2,5,3)
print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]


In [97]:
b[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [98]:
b[0,1]

array([3, 4, 5])

## DPP


In [99]:
# An e-commerce comapany recoreds the quantity sold and selling prices of 12 products .


In [100]:
quantity = np.array([2,5,3,8,4,6,10,1,7,5,9,3])
price = np.array([
    1200,800,1500,450,2200,900,
    700,1800,650,1300,500,2500
])

In [101]:
# calculate revenue for every product .
# calculate the total revenue .
# find the product index generating the highest revenue.
# extract the revenue of the last first five products.

In [102]:
rev = quantity*price

In [103]:
rev

array([2400, 4000, 4500, 3600, 8800, 5400, 7000, 1800, 4550, 6500, 4500,
       7500])

In [104]:
# calculate the total revenue .
np.sum(rev)

np.int64(60550)

In [105]:
# find the prooduct index generating the highest revenue .
np.argmax(rev)

np.int64(4)

In [106]:
# extract the revenue of the last five products .
rev[-5:]

array([1800, 4550, 6500, 4500, 7500])

In [107]:
# Find products whose revenue is above the average revenue.
# Apply a 10% discount only to products whose price is greater than ₹1,000.
# Round the discounted prices to two decimal places.
# Calculate the total quantity sold.
# Find the median product price.
# Identify products whose price is above the median and whose quantity is at least 5 .

In [108]:
avg_rev = np.mean(rev)

In [109]:
avg_rev

np.float64(5045.833333333333)

In [110]:
rev[rev>avg_rev]

array([8800, 5400, 7000, 6500, 7500])

In [111]:
np.where(rev>avg_rev , "Yes","No")

array(['No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes',
       'No', 'Yes'], dtype='<U3')

In [112]:
# Apply a 10 % discount only to products whose proces is greater then $ 1,000.
price

array([1200,  800, 1500,  450, 2200,  900,  700, 1800,  650, 1300,  500,
       2500])

In [113]:
discounted_p = np.where(price>1000,price*0.9,price)
print(discounted_p)

[1080.  800. 1350.  450. 1980.  900.  700. 1620.  650. 1170.  500. 2250.]


In [114]:
# Round the discounted prices to two decimal places .
discounted_p = np.round(discounted_p,2)
print(discounted_p)

[1080.  800. 1350.  450. 1980.  900.  700. 1620.  650. 1170.  500. 2250.]


In [115]:
# Calculate the total quantity sold .
np.sum(quantity)

np.int64(63)

In [116]:
# Find the medium produsct prices .
med_p = np.median(price)

In [117]:
# Identify products whose priced is above the median and whose is at least 5 .

In [118]:
criteria = (price>med_p)&(quantity>=5)

In [119]:
price[criteria]

array([1300])

In [120]:
# A college has performance scores for 24 assessments:

In [121]:
scores = np.array([
    72,81,65,90,
    77,88, 69, 91,
73, 84, 60, 75,
82, 79, 95, 68,
71, 86, 89, 93,
66, 74, 80, 87
])

In [122]:
# Assume there are 6 students and 4 assessments per students .

In [123]:
# verify the number of elements .
# reshape the array into a 6*6 matrix .
# calculate the average score for each students .
# Find the highest score achieved by each student.

In [124]:
np.size(scores)

24

In [125]:
# Reshape the array into a 6*4 matrix
new_s = scores.reshape(6,4)

In [126]:
new_s

array([[72, 81, 65, 90],
       [77, 88, 69, 91],
       [73, 84, 60, 75],
       [82, 79, 95, 68],
       [71, 86, 89, 93],
       [66, 74, 80, 87]])

In [127]:
np.mean(new_s,axis=1)

array([77.  , 81.25, 73.  , 81.  , 84.75, 76.75])

In [128]:
# Find the highest score achieved by each students .
np.max(new_s,axis=1)

array([90, 91, 84, 95, 93, 87])

In [126]:
# Find the student index having the highest overall average.
# Create performance labels:
# average >= 85 → "Excellent"
# average >= 70 → "Good"
# average >= 50 → "Pass"
# otherwise → "Fail"
# Extract students whose average is above the overall average

In [129]:
# Find the student index having the highest overall average .
avg_st=np.mean(new_s,axis=1)

In [130]:
a= np.argmax(avg_st)
print(a)

4


In [131]:
np.where(avg_st >= 85, "Excellent", np.where(avg_st >= 70, "Good", np.where(avg_st >= 50, "Pass", "Fail")))

array(['Good', 'Good', 'Good', 'Good', 'Good', 'Good'], dtype='<U9')

In [132]:
# Extract students whose average is above the overall average .
scores

array([72, 81, 65, 90, 77, 88, 69, 91, 73, 84, 60, 75, 82, 79, 95, 68, 71,
       86, 89, 93, 66, 74, 80, 87])

In [133]:
avg_sc = np.mean(scores)

In [134]:
ans = np.where(avg_st>avg_sc ,"  Yes " ," No ")

In [135]:
ans

array([' No ', '  Yes ', ' No ', '  Yes ', '  Yes ', ' No '], dtype='<U6')

In [ ]:
# Extract the last two assessments of every student.
# Flatten the complete matrix.
# Calculate the percentage of all assessment scores that are above 80.

In [136]:
new_s

array([[72, 81, 65, 90],
       [77, 88, 69, 91],
       [73, 84, 60, 75],
       [82, 79, 95, 68],
       [71, 86, 89, 93],
       [66, 74, 80, 87]])

In [138]:
new_s[:,-2:]

array([[65, 90],
       [69, 91],
       [60, 75],
       [95, 68],
       [89, 93],
       [80, 87]])

In [139]:
# Flatten the complete matrix .
scores.flatten()

array([72, 81, 65, 90, 77, 88, 69, 91, 73, 84, 60, 75, 82, 79, 95, 68, 71,
       86, 89, 93, 66, 74, 80, 87])

In [140]:
# Calculate the percentage of all assessment scores that are above 80 .
grt_80=scores[scores>80]

In [141]:
a = len(grt_80)
n = len(scores)
perc = a*100/n
print(perc)

45.833333333333336


In [ ]:
# A company's monthly sales for one year are:
# sales = np.array([
# 120000, 135000, 128000, 150000,
# 160000, 172000, 165000, 180000,
# 195000, 210000, 205000, 225000
# ])

In [ ]:
# Calculate the average monthly sales.
# Find the median sales.
# Find the month with the highest sales.
# Calculate the standard deviation.

In [142]:
sales = np.array([
    120000, 135000, 128000, 150000,
    160000, 172000, 165000, 180000,
    195000, 210000, 205000, 225000
])

In [143]:
np.mean(sales)

np.float64(170416.66666666666)

In [144]:
np.median(sales)

np.float64(168500.0)

In [145]:
#Find the month with highest sales
np.argmax(sales)

np.int64(11)

In [146]:
# Calculate the standard deviation .
np.std(sales)

np.float64(32392.021479919335)

In [ ]:
# Create a forecast for the next 6 months using np.linspace() between:
# the minimum observed sales
# and 20% above the maximum observed sales.
# Round the forecast values to the nearest rupee.
# Combine the original sales and forecast into one 18-element array.
# Reshape the combined array into 3 × 6.
# Calculate the average sales for each row.
# Identify values that are greater than the overall median.

In [149]:
mn_s = np.min(sales)
mx_s = np.max(sales)

In [150]:
mx_s20 = mx_s*1.2

In [153]:
forecast = np.linspace(mn_s,mx_s20,6)

In [154]:
# Round the forecast value to the nearest rupee .
r_s = np.round(forecast,2)

In [156]:
r_s

array([120000., 150000., 180000., 210000., 240000., 270000.])

In [157]:
sales

array([120000, 135000, 128000, 150000, 160000, 172000, 165000, 180000,
       195000, 210000, 205000, 225000])

In [159]:
n_s= np.append(sales,r_s)
n_s

array([120000., 135000., 128000., 150000., 160000., 172000., 165000.,
       180000., 195000., 210000., 205000., 225000., 120000., 150000.,
       180000., 210000., 240000., 270000.])

In [160]:
# Reshape the comnined array into 3 * 6 .
ans = n_s.reshape(3,6)
ans

array([[120000., 135000., 128000., 150000., 160000., 172000.],
       [165000., 180000., 195000., 210000., 205000., 225000.],
       [120000., 150000., 180000., 210000., 240000., 270000.]])

In [161]:
np.mean(ans,axis=1)

array([144166.66666667, 196666.66666667, 195000.        ])

In [162]:
np.where(n_s>np.median(n_s),"Yes","No")

array(['No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes',
       'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes'], dtype='<U3')

# HW

In [ ]:
# A factory collects temperatures from 20 sensor readings:
# temperature = np.array([
# 28.5, 31.2, 29.8, 35.6, 38.1,
# 40.2, 27.9, 30.5, 42.3, 39.8,
# 36.4, 33.2, 29.1, 41.7, 44.2,
# 31.8, 34.5, 37.6, 26.9, 43.1
# ])

In [ ]:
# Calculate mean, median, minimum and maximum.
# Calculate variance and standard deviation.
# Find all temperatures more than one standard deviation above the mean.
# Calculate the absolute difference between every temperature and the mean.
# Find the five readings having the largest deviation from the mean.
# # Round all temperatures to the nearest whole number.