<a href="https://colab.research.google.com/github/anjalitiwarics27-coder/aiml/blob/main/4_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import numpy as np

In [29]:
# # A factory collects temperatures from 20 sensor readings:
# temperature = np.array([
# 28.5, 31.2, 29.8, 35.6, 38.1,
# 40.2, 27.9, 30.5, 42.3, 39.8,
# 36.4, 33.2, 29.1, 41.7, 44.2,
# 31.8, 34.5, 37.6, 26.9, 43.1
# ])

In [30]:
# Calculate mean, median, minimum and maximum.
# Calculate variance and standard deviation.
# Find all temperatures more than one standard deviation above the mean.
# Calculate the absolute difference between every temperature and the mean.
# Find the five readings having the largest deviation from the mean.
# Round all temperatures to the nearest whole number

In [31]:
temperature = np.array([
    28.5, 31.2, 29.8, 35.6, 38.1,
    40.2, 27.9, 30.5, 42.3, 39.8,
    36.4, 33.2, 29.1, 41.7, 44.2,
    31.8, 34.5, 37.6, 26.9, 43.1
])


In [32]:
print(temperature)

[28.5 31.2 29.8 35.6 38.1 40.2 27.9 30.5 42.3 39.8 36.4 33.2 29.1 41.7
 44.2 31.8 34.5 37.6 26.9 43.1]


In [33]:
temperature.ndim

1

In [34]:
temperature.shape

(20,)

In [35]:
# Calculate mean, median, minimum and maximum.

In [36]:
avg_t = np.mean(temperature)
print(avg_t)

35.12


In [37]:
median_t = np.median(temperature)
print(median_t)

35.05


In [38]:
mnt = np.min(temperature)
print(mnt)

26.9


In [39]:
mxt = np.max(temperature)
print(mxt)

44.2


In [40]:
stdt=np.std(temperature)
print(stdt)

5.410415880503088


In [41]:
var = np.var(temperature)
print(var)

29.272600000000004


In [42]:
# Find all temperatures more than one standard deviation above the mean .



In [43]:
new_t = temperature[ temperature > (avg_t + stdt)]
new_t

array([42.3, 41.7, 44.2, 43.1])

In [44]:
np.where(temperature > (avg_t + stdt), "Yes","No")

array(['No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No',
       'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes'],
      dtype='<U3')

In [45]:
temperature

array([28.5, 31.2, 29.8, 35.6, 38.1, 40.2, 27.9, 30.5, 42.3, 39.8, 36.4,
       33.2, 29.1, 41.7, 44.2, 31.8, 34.5, 37.6, 26.9, 43.1])

In [46]:
# Calculate the absolute difference between every temperature and then mean .


In [47]:
deviation = np.abs(temperature - avg_t)
deviation

array([6.62, 3.92, 5.32, 0.48, 2.98, 5.08, 7.22, 4.62, 7.18, 4.68, 1.28,
       1.92, 6.02, 6.58, 9.08, 3.32, 0.62, 2.48, 8.22, 7.98])

In [48]:
# Find the five readings having the largest deviation from the mean .
largest_deviation= np.sort(deviation)

In [49]:
largest_deviation

array([0.48, 0.62, 1.28, 1.92, 2.48, 2.98, 3.32, 3.92, 4.62, 4.68, 5.08,
       5.32, 6.02, 6.58, 6.62, 7.18, 7.22, 7.98, 8.22, 9.08])

In [50]:
large5= largest_deviation[-5:]

In [51]:
# Round all temperature to the nearest whole number .
temperature

array([28.5, 31.2, 29.8, 35.6, 38.1, 40.2, 27.9, 30.5, 42.3, 39.8, 36.4,
       33.2, 29.1, 41.7, 44.2, 31.8, 34.5, 37.6, 26.9, 43.1])

In [52]:
np.round(temperature)

array([28., 31., 30., 36., 38., 40., 28., 30., 42., 40., 36., 33., 29.,
       42., 44., 32., 34., 38., 27., 43.])

In [53]:
# Categorize temperatures:
# >= 40 → "Critical"
# >= 35 → "Warning"
# Otherwise → "Normal"
# Find the number and percentage of critical readings.
# Reshape the readings into a 4 × 5 array.
# # Find the average temperature for each row.

In [54]:
cat_t = np.where(temperature >= 40, "Critical", np.where(temperature >= 35, "Warning", "Normal"))
cat_t

array(['Normal', 'Normal', 'Normal', 'Warning', 'Warning', 'Critical',
       'Normal', 'Normal', 'Critical', 'Warning', 'Warning', 'Normal',
       'Normal', 'Critical', 'Critical', 'Normal', 'Normal', 'Warning',
       'Normal', 'Critical'], dtype='<U8')

In [55]:
temperature

array([28.5, 31.2, 29.8, 35.6, 38.1, 40.2, 27.9, 30.5, 42.3, 39.8, 36.4,
       33.2, 29.1, 41.7, 44.2, 31.8, 34.5, 37.6, 26.9, 43.1])

In [56]:
critical_t = cat_t[cat_t == "Critical "]

In [57]:
c = len(critical_t)
c

0

In [58]:
n = len(cat_t)
n

20

In [59]:
perc = c*100/n
perc

0.0

In [60]:
# Reshape the readings into a 4 × 5 array.

In [61]:
new_t = temperature.reshape(4,5)
new_t

array([[28.5, 31.2, 29.8, 35.6, 38.1],
       [40.2, 27.9, 30.5, 42.3, 39.8],
       [36.4, 33.2, 29.1, 41.7, 44.2],
       [31.8, 34.5, 37.6, 26.9, 43.1]])

In [62]:
# Find the average temperature for each row .
np.mean(new_t,axis=1)

array([32.64, 36.14, 36.92, 34.78])

In [ ]:
# Consider the following employee data:
# employees = np.array([
# [101, 42000, 3, 450000],
# [102, 65000, 6, 720000],
# [103, 38000, 2, 300000],
# [104, 90000, 8, 950000],
# [105, 55000, 5, 610000],
# [106, 72000, 7, 830000]
# ])
# Columns represent:
# Employee_ID
# Salary
# Experience
# Annual_Sales

In [ ]:
# Extract salary, experience and annual sales.
# Calculate sales-to-salary ratio.
# Find the employee with the highest annual sales.
# Find employees having at least 5 years experience AND sales above ₹600,000.
# Calculate bonus:
# Sales >= ₹800,000 → 10%
# Sales >= ₹600,000 → 7%
# Otherwise → 3%

In [63]:
employees = np.array([
    [101, 42000, 3, 450000],
    [102, 65000, 6, 720000],
    [103, 38000,2,300000],
    [104, 90000,8,950000],
    [105, 55000,5,610000],
    [106, 72000,7,830000]
])

In [64]:
# Extract salary , experience and annual sales .
salary = employees[:,1]
experience = employees[:,2]
sales = employees[:,3]

In [65]:
salary

array([450000, 720000, 300000, 950000, 610000, 830000])

In [66]:
experience

array([3, 6, 2, 8, 5, 7])

In [67]:
sales

array([450000, 720000, 300000, 950000, 610000, 830000])

In [68]:
# Calculate sales-to-salary ratio .
sts = np.round(sales/salary)
sts

array([11., 11.,  8., 11., 11., 12.])

In [69]:
# Find the employee with highest annual sales .
np.argmax(sales)

np.int64(3)

In [70]:
employees[np.argmax(sales)]

array([   104,  90000,      8, 950000])

In [ ]:
# Find employees having at least 5 years experience AND sales above $ 6,00,000

In [71]:
criteria = (experience >= 5) & (sales > 600000)
criteria

array([False,  True, False,  True,  True,  True])

In [72]:
employees[criteria]

array([[   102,  65000,      6, 720000],
       [   104,  90000,      8, 950000],
       [   105,  55000,      5, 610000],
       [   106,  72000,      7, 830000]])

In [ ]:
# calculate bonus :
# sales >= $ 800,000 → 10%
# sales >= $ 600,000 → 7%
# otherwise → 3%

In [73]:
bonus = np.where(sales>= 800000, 0.1*sales, np.where(sales >= 600000, 0.07*sales, 0.03*sales))
bonus

array([13500., 50400.,  9000., 95000., 42700., 83000.])

In [ ]:
# Calculate total bonus amount.
# Find average salary of employees receiving a 10% bonus.
# Find median salary.
# Find employees whose salary is above median salary but experience is less than 6 years.
# Round sales-to-salary ratio to 2 decimal places.

In [74]:
# Calculate total bonus amount .
total_bonus = np.sum(bonus)
total_bonus

np.float64(293600.0)

In [75]:
# Find average salary of employees receiving a 10 % bonus .
sales >= 800000

array([False, False, False,  True, False,  True])

In [76]:
s = salary[sales >= 800000]
s

array([90000, 72000])

In [77]:
np.mean(s)

np.float64(81000.0)

In [78]:
# Find median salary .
np.median(salary)

np.float64(60000.0)

In [79]:
median_s = np.median(salary)
median_s

np.float64(60000.0)

In [80]:
# Find employees whose salary is above median salary but experience is less than 6 years.
criteria = (salary > median_s) & (experience < 6)
criteria

array([False, False, False, False, False, False])

In [82]:
employees[criteria]

array([], shape=(0, 4), dtype=int64)

In [83]:
#  Round sales -to- salary ratio to 2 decimal places .

In [84]:
sts

array([11., 11.,  8., 11., 11., 12.])

In [86]:
sts2 = np.round(sales/salary,2)
sts2

array([10.71, 11.08,  7.89, 10.56, 11.09, 11.53])

In [ ]:
# Consider the following 6 × 6 grayscale image:
# image = np.array([
# [10, 25, 40, 55, 70, 85],
# [20, 35, 50, 65, 80, 95],
# [30, 45, 60, 75, 90, 105],
# [40, 55, 70, 85, 100, 115],
# [50, 65, 80, 95, 110, 125],
# [60, 75, 90, 105, 120, 135]
# ])

In [ ]:
# Find ndim , shape and size .
# Extract the central 4 × 4 region.
# Increase the central region by 20%.
# Cap all pixel values above 100 at 100.
# Find mean, minimum and maximum pixel values.

In [87]:
image = np.array([
[10, 25, 40, 55, 70, 85],
[20, 35, 50, 65, 80, 95],
[30, 45, 60, 75, 90, 105],
[40, 55, 70, 85, 100, 115],
[50, 65, 80, 95, 110, 125],
[60, 75, 90, 105, 120, 135]
])

In [ ]:
# Find ndim, shape and size.

In [88]:
image.ndim

2

In [89]:
image.shape

(6, 6)

In [90]:
image.size

36

In [91]:
image

array([[ 10,  25,  40,  55,  70,  85],
       [ 20,  35,  50,  65,  80,  95],
       [ 30,  45,  60,  75,  90, 105],
       [ 40,  55,  70,  85, 100, 115],
       [ 50,  65,  80,  95, 110, 125],
       [ 60,  75,  90, 105, 120, 135]])

In [92]:
# cap all pixel values above 100 at 100 .
image = np.where(image > 100, 100, image)
image

array([[ 10,  25,  40,  55,  70,  85],
       [ 20,  35,  50,  65,  80,  95],
       [ 30,  45,  60,  75,  90, 100],
       [ 40,  55,  70,  85, 100, 100],
       [ 50,  65,  80,  95, 100, 100],
       [ 60,  75,  90, 100, 100, 100]])

In [93]:
# Find mean , minimum and maximum pixel values .
np.mean(image)

np.float64(69.30555555555556)

In [94]:
np.min(image)

np.int64(10)

In [95]:
np.max(image)

np.int64(100)

In [ ]:
# Find pixels above the 75th percentile.
# Flatten the image.
# Find pixels below the overall mean.
# Reshape the flattened array back into 6 × 6.

In [96]:
# Find pixels above the 75th percentile.
p75 = np.percentile(image, 75)
p75

np.float64(95.0)

In [97]:
image[image>p75]

array([100, 100, 100, 100, 100, 100, 100, 100])

In [98]:
avg = np.mean(image)

In [99]:
image[image<avg]

array([10, 25, 40, 55, 20, 35, 50, 65, 30, 45, 60, 40, 55, 50, 65, 60])

In [100]:
image.flatten()

array([ 10,  25,  40,  55,  70,  85,  20,  35,  50,  65,  80,  95,  30,
        45,  60,  75,  90, 100,  40,  55,  70,  85, 100, 100,  50,  65,
        80,  95, 100, 100,  60,  75,  90, 100, 100, 100])

In [101]:
new_image = image.reshape(6,6)
new_image

array([[ 10,  25,  40,  55,  70,  85],
       [ 20,  35,  50,  65,  80,  95],
       [ 30,  45,  60,  75,  90, 100],
       [ 40,  55,  70,  85, 100, 100],
       [ 50,  65,  80,  95, 100, 100],
       [ 60,  75,  90, 100, 100, 100]])