<a href="https://colab.research.google.com/github/anjalitiwarics27-coder/aiml/blob/main/4_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Earners AIML by Aditya Jain sir - numpy 4.2

In [5]:
a=[3,5.6,"aj",True]
type(a)

list

In [6]:
print(a)

[3, 5.6, 'aj', True]


In [7]:
import numpy as np
b=np.array(a)
print(b)

['3' '5.6' 'aj' 'True']


In [8]:
a=[4,6,2,9]
b=np.array(a)
type(a)

list

In [9]:
type(b)

numpy.ndarray

In [10]:
b+2

array([ 6,  8,  4, 11])

In [11]:
b*2


array([ 8, 12,  4, 18])

In [12]:
a=np.array([4,3,1])
b=np.array([5,4,2])
a+b

array([9, 7, 3])

In [13]:
a-b

array([-1, -1, -1])

In [14]:
a*b

array([20, 12,  2])

In [15]:
# given a list of prices , update then with gst included prices

In [16]:
prices=[50,100,40,90,80]
gst_p=[]
for p in prices:
  gst_p.append(p+0.18*p)
print(gst_p)

[59.0, 118.0, 47.2, 106.2, 94.4]


In [17]:
np_prices=np.array(prices)
gst_np=np_prices*1.18

In [18]:
print(gst_np)

[ 59.  118.   47.2 106.2  94.4]


In [19]:
v=np.arange(1,10)
print(v)

[1 2 3 4 5 6 7 8 9]


In [20]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [21]:
num=(4,6,3,1)
a=np.array(num)
print(a)

[4 6 3 1]


In [22]:
type(a)

numpy.ndarray

In [23]:
type(b)

numpy.ndarray

In [24]:
type(num)

tuple

In [25]:
a=np.array([5,4,5.5,9])

In [26]:
a

array([5. , 4. , 5.5, 9. ])

In [27]:
names=np.array(["aj","riya","raj","rahul"])
print(names)

['aj' 'riya' 'raj' 'rahul']


In [28]:
type(names)

numpy.ndarray

In [29]:
a=np.array([True,False,False])
print(a)

[ True False False]


In [30]:
type(a)

numpy.ndarray

In [31]:
marks=np.array([
    [70,80,90],
    [60,75,85]
])

In [32]:
marks[0,1] # in numpy

np.int64(80)

In [33]:
marks[0][1] # in python

np.int64(80)

In [34]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [35]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [36]:
np.ones(5)*5

array([5., 5., 5., 5., 5.])

In [37]:
np.full(6,2)

array([2, 2, 2, 2, 2, 2])

In [38]:
np.full((3,4),2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [39]:
# 0-10 all even numbers :
# linespace ,arange

In [40]:
a=np.arange(0,11,2)
print(a)

[ 0  2  4  6  8 10]


In [41]:
b=np.linspace(0,10,6)
print(b)

[ 0.  2.  4.  6.  8. 10.]


In [42]:
print(b.dtype)

float64


In [43]:
a.dtype

dtype('int64')

In [44]:
a=np.array([True,False])
a.dtype

dtype('bool')

In [45]:
b=np.array([4,6,3.5])
b.dtype

dtype('float64')

In [46]:
a=np.array([10,20,30],dtype=float)
print(a)

[10. 20. 30.]


In [47]:
a.dtype

dtype('float64')

In [48]:
b=np.array([10.5,4.7,7],dtype=int)
print(b)

[10  4  7]


In [49]:
c=np.array([2,4,0,7,0],dtype=bool)
print(c)

[ True  True False  True False]


In [50]:
import numpy as np
marks=np.array([60,70,80,90,100])
bonus=marks+5
final_marks=bonus*1
print(marks)
print(bonus)
print(final_marks)

[ 60  70  80  90 100]
[ 65  75  85  95 105]
[ 65  75  85  95 105]


In [51]:
import numpy as np
numbers=[10,20,30]
arr=np.array(numbers)
array_result=arr*2
print(array_result)

[20 40 60]


In [52]:
import numpy as np
numbers=[10,20,30]
list_result=numbers*2
arr=np.array(numbers)
array_result=arr*2
print(array_result)
print(list_result)

[20 40 60]
[10, 20, 30, 10, 20, 30]


In [53]:
import numpy as np
prices=np.array([100,200,300,400,500])
discount =prices*0.10
final_price=prices-discount
print(discount)
print(final_price)

[10. 20. 30. 40. 50.]
[ 90. 180. 270. 360. 450.]


In [54]:
numbers=np.arange(2,21,3)
print(numbers)

[ 2  5  8 11 14 17 20]


In [56]:
import numpy as np
numbers=np.arange(2,21,3)
print("numbers ",numbers)
print(numbers[0])
print(numbers[-1])
print(len(numbers))
print(numbers*2)

numbers  [ 2  5  8 11 14 17 20]
2
20
7
[ 4 10 16 22 28 34 40]


In [57]:
import numpy as np
values=np.linspace(0,20,5)
print(values)
doubled=values*2
print(doubled)
print(values+10)
print(values/2)

[ 0.  5. 10. 15. 20.]
[ 0. 10. 20. 30. 40.]
[10. 15. 20. 25. 30.]
[ 0.   2.5  5.   7.5 10. ]


In [58]:
import numpy as np
attendence =np.zeros(5)
print(attendence)
attendence=attendence+5
print(attendence)
attendence=attendence+3
print(attendence)
attendence=attendence*2
print(attendence)

[0. 0. 0. 0. 0.]
[5. 5. 5. 5. 5.]
[8. 8. 8. 8. 8.]
[16. 16. 16. 16. 16.]


In [59]:
import numpy as np
salary = np.full(5,30000)
print(salary)
increment = salary *0.10
print(increment)
new_salary=salary+increment
print(new_salary)
print(new_salary*2)

[30000 30000 30000 30000 30000]
[3000. 3000. 3000. 3000. 3000.]
[33000. 33000. 33000. 33000. 33000.]
[66000. 66000. 66000. 66000. 66000.]


In [60]:
import numpy as np
arr=np.array([10,20,30.5,40,50])
print(arr)
result=arr*2
print(result)
print(result.dtype)

[10.  20.  30.5 40.  50. ]
[ 20.  40.  61.  80. 100.]
float64


In [61]:
import numpy as np
marks=np.array([
    [70,80,90],
    [60,75,85]
])
print(marks)
print(marks+5)
print(marks*2)
print(marks-10)

[[70 80 90]
 [60 75 85]]
[[75 85 95]
 [65 80 90]]
[[140 160 180]
 [120 150 170]]
[[60 70 80]
 [50 65 75]]


In [62]:
import numpy as np
a=np.array([10,20,30,40])
b=np.array([1,2,3,4])
addition =a+b
subtraction=a-b
multiplication=a*b
division=a/b
print(addition)
print(subtraction)
print(multiplication)
print(division)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


In [63]:
import numpy as np
a=np.array([10,20,30,40])
b=np.array([1,2,3])
addition =a+b
subtraction=a-b
multiplication=a*b
division=a/b
print(addition)
print(subtraction)
print(multiplication)
print(division)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [ ]:
# be broadcast together with shapes (4,) (3,)

In [64]:
import numpy as np
salary = np.array([30000,40000,50000,60000])
increment=salary*0.20
new_salary=salary+increment
print(salary)
print(increment)
print(new_salary)
bonus=new_salary*0.05
print(bonus)

[30000 40000 50000 60000]
[ 6000.  8000. 10000. 12000.]
[36000. 48000. 60000. 72000.]
[1800. 2400. 3000. 3600.]


In [65]:
new_salary+bonus

array([37800., 50400., 63000., 75600.])

In [67]:
numbers=np.arange(2,21,2)
print(numbers)

[ 2  4  6  8 10 12 14 16 18 20]


In [68]:
import numpy as np
numbers=np.arange(2,21,2)
print(numbers)
result =numbers+1
print(result)
result=result * 2
print(result)
print(len(numbers))

[ 2  4  6  8 10 12 14 16 18 20]
[ 3  5  7  9 11 13 15 17 19 21]
[ 6 10 14 18 22 26 30 34 38 42]
10


In [69]:
import numpy as np
a= np.arange(0,11,2)
b=np.linspace(0,10,6)
print(a)
print(b)
print(a*2)
print(b*2)
print(len(a))
print(len(b))

[ 0  2  4  6  8 10]
[ 0.  2.  4.  6.  8. 10.]
[ 0  4  8 12 16 20]
[ 0.  4.  8. 12. 16. 20.]
6
6


In [ ]:
# linspace gives always floating value beacuse its divison , it division for specific task

#HW

In [70]:
import numpy as np
a=np.array([1,2,3])
b=np.array([1.5,2.5,3.5])
print(a.dtype)
print(b.dtype)
c=a+b
print(c)
print(a.dtype)

int64
float64
[2.5 4.5 6.5]
int64


In [72]:
import numpy as np
arr=np.array([10.5,20.7,30.9],dtype=int)
print(arr)
print(arr.dtype)
result=arr+5
print(result)
print(result*2)

[10 20 30]
int64
[15 25 35]
[30 50 70]


In [74]:
import numpy as np
arr=np.array([0,1,2,0,5],dtype=bool)
print(arr)
result =arr*1
print(result)
result= result+5
print(result)
print(result.dtype)

[False  True  True False  True]
[0 1 1 0 1]
[5 6 6 5 6]
int64


In [75]:
import numpy as np
arr=np.zeros((3,4))
print(arr)
print(arr+10)
print(arr*5)
print(arr+100)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[100. 100. 100. 100.]
 [100. 100. 100. 100.]
 [100. 100. 100. 100.]]
