<a href="https://colab.research.google.com/github/anjalitiwarics27-coder/aiml/blob/main/4_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Earners AIML by Aditya Jain sir - numpy 4.3

##Challenge Questions -DPP

In [ ]:
import numpy as np
arr=np.ones((2,3))
print(arr)
result=arr*10
print(result)
result=result+5
print(result)
result=result/5
print(result)

[[1. 1. 1.]
 [1. 1. 1.]]
[[10. 10. 10.]
 [10. 10. 10.]]
[[15. 15. 15.]
 [15. 15. 15.]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [ ]:
import numpy as np
arrr=np.full(4,50)
print(arr)
arr=arr+20
print(arr)
arr=arr*2
print(arr)
arr=arr-10
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]
[[21. 21. 21.]
 [21. 21. 21.]]
[[42. 42. 42.]
 [42. 42. 42.]]
[[32. 32. 32.]
 [32. 32. 32.]]


In [ ]:
import numpy as np
celsius=np.array([0,10,20,30,40])
f=celsius*(9/5)+32
print(f)
print(celsius)

[ 32.  50.  68.  86. 104.]
[ 0 10 20 30 40]


In [ ]:
#  A student has scored
# 65 ,72,80,88,91
# create a NumPy array containing these marks
#Add 5 bonus marks to every subject and display the original marks and update marks.


In [ ]:
import numpy as np
marks=np.array([65,72,80,88,91])
bonus=5
print(marks)
marks=marks+bonus
print(marks)

[65 72 80 88 91]
[70 77 85 93 96]


In [ ]:
# A shop has five products with prices
100,250,400,550,800
# Create a Numpy array
# and claculate the price after applying a 10% discount to each product.

(100, 250, 400, 550, 800)

In [ ]:
import numpy as np
product = np.array([100,250,400,550,800])
Amount=product-product*0.10
print("dicount : ",Amount)
print("product real amount : ",product)

dicount :  [ 90. 225. 360. 495. 720.]
product real amount :  [100 250 400 550 800]


In [ ]:
import numpy as np
product = np.array([100,250,400,550,800])
Amount=product*0.90
print("dicount : ",Amount)
print("product real amount : ",product)

dicount :  [ 90. 225. 360. 495. 720.]
product real amount :  [100 250 400 550 800]


In [ ]:
# A company has 5 employees with salary
# 30000 ,35000,40000,45000,50000
# create an array and give employees a 10% salary increment .

In [ ]:
import numpy as np
salary=np.array([30000,35000,40000,45000,50000])
increment=salary*1.10
print("increment : ",increment)
print("salary : ",salary)

increment :  [33000. 38500. 44000. 49500. 55000.]
salary :  [30000 35000 40000 45000 50000]


In [ ]:
# A student's marks are stored in a tuple:
# (78,85,92,67,88)
# convert the tuple into a NumPy array and add 3 marks to every value

In [ ]:
a=(78,85,92,67,88)
np_a=np.array(a)
print(np_a+3)


[81 88 95 70 91]


In [ ]:
# A company records sales for the quarters:
# q1 = 125000
# q2=148000
# q3=135000
# q4=172000
# create a numpy array
# The company expects next year's sales to be 15% higher than this year' sales . Calculate the expected sales for each
# then calculate the additional sales expected in each quarter .

In [ ]:
import numpy as np
sales = np.array([125000,148000,135000,172000])
new_sales=sales*1.5
additional_sales=new_sales-sales
print(new_sales)
print(additional_sales)

[187500. 222000. 202500. 258000.]
[62500. 74000. 67500. 86000.]


In [ ]:
import numpy as np
sales = np.array([125000,148000,135000,172000])
new_sales=sales*1.15
additional_sales= sales *0.15
print(new_sales)
print(additional_sales)

[143750. 170200. 155250. 197800.]
[18750. 22200. 20250. 25800.]


In [ ]:
# Two branches of a comapny have inventory for five products .
# Branch A = [120,150,180,100,200]
# Branch B =[80,130,170,120,150]
# Create two Numpy np.arrays
# Calculate :
# Total inventory for each product.
# Difference between Branch A and Branch B.
# Comnined inventory after reciving an aditional 20 units of every products.

In [ ]:
A= np.array([120,150,180,100,200])
B=np.array([80,130,170,120,150])
print("Total inventory : ",A+B)
print("Difference : ",A-B)
print("Additional 20 Units : ",A+B+20)

Total inventory :  [200 280 350 220 350]
Difference :  [ 40  20  10 -20  50]
Additional 20 Units :  [220 300 370 240 370]


In [ ]:
# A store sells four products.
# prices:
# [250,400,750,1200]
# unit sold :
# [12,8,5,10]
# calculate the revenue generated by each product.
# The store then wants to increase the revenue figures by 5% for forecasting purposes .

In [ ]:
import numpy as np
prices =np.array([250,400,750,1200])
units = np.array([12,8,5,10])
revenue = prices * units
forecast = revenue * 1.05
print("revenue : " , revenue)
print("forecast: ",forecast)

revenue :  [ 3000  3200  3750 12000]
forecast:  [ 3150.   3360.   3937.5 12600. ]


In [ ]:
import numpy as np
marks = np.array([70,80,65,90,85])
print(marks)

[70 80 65 90 85]


In [ ]:
len(marks)

5

In [ ]:
arr2=np.array([
    [80,75,90],
    [70,85,88],
    [92,90,95]
])
print(arr2)

[[80 75 90]
 [70 85 88]
 [92 90 95]]


In [ ]:
marks.ndim # array dimention

1

In [ ]:
arr2.ndim

2

In [ ]:
arr3=np.array([
    [
    [8,75,90],
    [70,85,88],
    [92,90,95]
],
    [
         [8,75,90],
    [70,85,88],
    [92,90,95]
    ]
    ])
print(arr3)

[[[ 8 75 90]
  [70 85 88]
  [92 90 95]]

 [[ 8 75 90]
  [70 85 88]
  [92 90 95]]]


In [ ]:
print(arr3)

[[[ 8 75 90]
  [70 85 88]
  [92 90 95]]

 [[ 8 75 90]
  [70 85 88]
  [92 90 95]]]


In [ ]:
print(arr3.ndim)

3


In [ ]:
sales = np.array([
    [100,120,150,200],
    [130,180,160,150],
    [200,220,250,170]
])
print(sales)
print(sales.ndim)

[[100 120 150 200]
 [130 180 160 150]
 [200 220 250 170]]
2


In [ ]:
sales.shape

(3, 4)

In [ ]:
sales.size

12

In [ ]:
len(sales)

3

In [ ]:
arr=np.array([10.5,20.7,30.9])
arr_int=arr.astype(int)
print(arr)

[10.5 20.7 30.9]


In [ ]:
print(arr_int)

[10 20 30]


In [ ]:
# dtype ->original arrays ko change krnta h jabki astype na copy array mein changes krta hein

In [ ]:
data=np.array([
    [10,20,30,40],
    [50,60,70,80],
    [90,100,110,120]
])
print("len : ",len(data))
print("size : ",data.size)
print("shape : ",data.shape)
print("ndim : ",data.ndim)

len :  3
size :  12
shape :  (3, 4)
ndim :  2


In [ ]:
# the array
# number of dimensions
# shape
# data type
# number of  students
# number of subjects

In [ ]:
student_marks=np.array([
    [78,85,90,88,96],
    [78,85,90,88,76],
    [78,85,90,88,76],
    [78,85,90,88,76],
    [78,85,90,88,76]
])
print(student_marks)
print(student_marks.ndim)
print(student_marks.shape)
print(student_marks.size)
print(student_marks.dtype)
print(student_marks.shape[0])
print(student_marks.shape[1])

[[78 85 90 88 96]
 [78 85 90 88 76]
 [78 85 90 88 76]
 [78 85 90 88 76]
 [78 85 90 88 76]]
2
(5, 5)
25
int64
5
5


In [ ]:
# A college wants to initialize a marks table for 5 students and 4 subjects
# initially , every student's marks are set to zero
# create This using np
# the create another 5*4 array containing a default value of 50

In [ ]:
student_marks = np.zeros((5,4))
print(student_marks)
print((student_marks +50))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[50. 50. 50. 50.]
 [50. 50. 50. 50.]
 [50. 50. 50. 50.]
 [50. 50. 50. 50.]
 [50. 50. 50. 50.]]


In [ ]:
updated = np.full((5,4),50)
print(updated)

[[50 50 50 50]
 [50 50 50 50]
 [50 50 50 50]
 [50 50 50 50]
 [50 50 50 50]]


In [ ]:
# Five students have scores:
# [45,56,67,78,89]
# the teacher gives everyone 3 grace marks .
# after that , the college applies a 10% scling factor to the adjust acores.
# calculate the final score

In [ ]:
import numpy as np
scores = np.array([45,56,67,78,89])
grace = scores+3
adjusted=scores*0.10
final_scores=scores*1.1
print(adjusted)
print(grace)
print(final_scores)

[4.5 5.6 6.7 7.8 8.9]
[48 59 70 81 92]
[49.5 61.6 73.7 85.8 97.9]


In [ ]:
import numpy as np
scores= np.array([45,56,67,78,89])
grace= scores+3
final_scores=scores*1.1
print(grace)
print(final_scores)

[48 59 70 81 92]
[49.5 61.6 73.7 85.8 97.9]


In [ ]:
# A company wants to set targets from $ 20,000 to $ 1,00,000
# generate exactly 9 target values , equally spaced.
# then create actual sales :
# [18000,28000,39000,47000,57000,66000,76000,90000,105000]
# calculate the difference between actual and target

In [ ]:
import numpy as np
targets = np.linspace(20000,100000,9)
actual_sales=np.array([
    18000,28000,39000,47000,57000,66000,76000,90000,105000
])
difference = (actual_sales - targets).astype(int)
print(targets)
print(actual_sales)
print(difference)
print(difference.dtype)

[ 20000.  30000.  40000.  50000.  60000.  70000.  80000.  90000. 100000.]
[ 18000  28000  39000  47000  57000  66000  76000  90000 105000]
[-2000 -2000 -1000 -3000 -3000 -4000 -4000     0  5000]
int64


In [ ]:
# A dataset contains :
# [10,20,30.5,40,50.75]
# create a numpy and display its data type.
# then create an integer version of the array.
# finally , multiply the integer array by 3 .

In [ ]:
import numpy as np
arr=np.array([10,20,30.5,40,50.75])
print(arr)
print(arr.dtype)
arr_int=arr.astype(int)
print(arr_int)
print(arr_int*3)

[10.   20.   30.5  40.   50.75]
float64
[10 20 30 40 50]
[ 30  60  90 120 150]


In [ ]:
# A company has product prices :
# [499,799,1299,2499]
# the company wants to :
# increase all prices by 12%
# and $50 packinging charges .
# calculate the final customer price.

In [ ]:
import numpy as np
prices = np.array([499,799,1299,2499])
inc_prices = prices*1.12
final_customer = inc_prices+50
print(inc_prices)
print(final_customer)


[ 558.88  894.88 1454.88 2798.88]
[ 608.88  944.88 1504.88 2848.88]


#hw

In [ ]:
# A website offers:
# First discount: 10%
# Second discount: 5% on the already discounted price
# Prices:
# [1000, 2000, 3000, 4000]
# Calculate the final prices.

In [1]:
import numpy as np
prices = np.array([1000,2000,3000,4000])
FirstDiscount= prices*0.9
SecondDiscount= FirstDiscount*0.95
print(FirstDiscount)
print(SecondDiscount)

[ 900. 1800. 2700. 3600.]
[ 855. 1710. 2565. 3420.]


In [ ]:
# A business has monthly revenue:
# [80000, 95000, 110000, 125000, 140000, 155000]
# The expected growth rate is 12%.
# Calculate:
# Expected increase.
# Forecast revenue.
# Create a target revenue array using linspace() from ₹80,000 to ₹1,60,000 with exactly 6 values.
# Compare forecast revenue with the target.

In [2]:
import numpy as np
revenue = np.array([80000,95000,110000,125000,140000,155000])
expected_increase = revenue*1.12
forecast_revenue = revenue+expected_increase
target = np.linspace(80000,160000,6)
print(expected_increase)
print(forecast_revenue)
print(target)

[ 89600. 106400. 123200. 140000. 156800. 173600.]
[169600. 201400. 233200. 265000. 296800. 328600.]
[ 80000.  96000. 112000. 128000. 144000. 160000.]


In [ ]:
# A factory wants to generate production quantities starting from 100 units, increasing by 50 units each day, for 10 days.
# Create the array using arange().
# Then increase every production target by 10%

In [3]:
import numpy as np
production=np.arange(100,1000,50)
print(production)
print(production*1.1)

[100 150 200 250 300 350 400 450 500 550 600 650 700 750 800 850 900 950]
[ 110.  165.  220.  275.  330.  385.  440.  495.  550.  605.  660.  715.
  770.  825.  880.  935.  990. 1045.]
