<a href="https://colab.research.google.com/github/anjalitiwarics27-coder/aiml/blob/main/4_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
marks = np.array([70,80,65,90,75])
print(marks.dtype)

int64


In [3]:
print(marks.ndim)

1


In [4]:
print(marks.shape)

(5,)


In [5]:
print(marks.size)

5


In [6]:
marks

array([70, 80, 65, 90, 75])

In [7]:
marks[0]

np.int64(70)

In [8]:
print(marks[3])

90


In [9]:
n=len(marks)
for i in range(n):
  print(marks[i] , end =" ")

70 80 65 90 75 

In [10]:
print(marks[n-1])

75


In [11]:
print(marks[-1])

75


In [12]:
print(marks[-2])

90


In [13]:
marks[2] = marks[2]+5


In [14]:
print (marks)

[70 80 70 90 75]


In [15]:
marks+5

array([75, 85, 75, 95, 80])

In [17]:
marks=np.array([
    [70,80,90],
    [60,75,85],
    [88,9,95]
])
print(marks)

[[70 80 90]
 [60 75 85]
 [88  9 95]]


In [20]:
print(marks[0,2])

90


In [21]:
marks[0,2]

np.int64(90)

In [ ]:
# print all the original elements of the 2d np arrray

In [22]:
marks

array([[70, 80, 90],
       [60, 75, 85],
       [88,  9, 95]])

In [ ]:
# A college stores marks of 4 students in 3 subjects: Maths, Science, and English.
# import numpy as np
# marks = np.array([
# [72, 85, 90],
# [65, 78, 82],
# [88, 91, 84],
# [70, 76, 80]
# ])
# Perform the following:
# Display the marks of the third student.
# Display the Science marks of the second student.
# Add 5 bonus marks to every student's English marks.
# Change the Maths marks of the fourth student to 75.
# Display the final marks array.

In [33]:
import numpy as np
marks = np.array([
    [72, 85, 90],
[65, 78, 82],
[88, 91, 84],
[70, 76, 80]
])
print(marks[2])
print(marks[1,1])
marks[:,2]+=5
print(marks)
marks[3,0]=75
print(marks)

[88 91 84]
78
[[72 85 95]
 [65 78 87]
 [88 91 89]
 [70 76 85]]
[[72 85 95]
 [65 78 87]
 [88 91 89]
 [75 76 85]]


In [29]:
import numpy as np

marks = np.array([
    [72, 85, 90],
    [65, 78, 82],
    [88, 91, 84],
    [70, 76, 80]
])

# 1. Display marks of the 3rd student (index 2)
print("3rd Student Marks:", marks[2])

# 2. Display Science marks (column index 1) of the 2nd student (row index 1)
print("2nd Student Science Marks:", marks[1, 1])

# 3. Add 5 bonus marks to every student's English marks (column index 2)
marks[:, 2] += 5
print(marks)
# 4. Change Maths marks (column index 0) of the 4th student (row index 3) to 75
marks[3, 0] = 75

# 5. Display final array
print("\nFinal Marks Array:")
print(marks)

3rd Student Marks: [88 91 84]
2nd Student Science Marks: 78
[[72 85 95]
 [65 78 87]
 [88 91 89]
 [70 76 85]]

Final Marks Array:
[[72 85 95]
 [65 78 87]
 [88 91 89]
 [75 76 85]]


In [43]:
marks = np.array([
[72, 85, 90],
[65, 78, 82],
[88, 91, 84],
[70, 76, 80]
])

In [44]:
# display the marks of the third students .
marks[2]

array([88, 91, 84])

In [45]:
# Display the Science marks of the second student .
marks[1,1]

np.int64(78)

In [41]:
# Add 5 bonus marks to every student's English marks.

In [46]:
marks[:,2]

array([90, 82, 84, 80])

In [47]:
marks[:,2] = marks[:,2]+5

In [48]:
marks

array([[72, 85, 95],
       [65, 78, 87],
       [88, 91, 89],
       [70, 76, 85]])

In [ ]:
# Change the Maths marks of the fourth students to 75

In [ ]:
marks[3,0] =75

In [49]:
# display the final marks of the arrays
print(marks)

[[72 85 95]
 [65 78 87]
 [88 91 89]
 [70 76 85]]


In [ ]:
# A company records monthly sales for 3 months
# The columns represent january , february  and march


# import numpy as np
# sales = np.array([
# [120, 150, 180],
# [100, 130, 160],
# [200, 220, 250]
# ])
# Perform the following:
# Display the complete sales data of Branch 2.
# Display the sales of all branches in February.
# Increase the March sales of every branch by 10%.
# The January sales of Branch 1 were entered incorrectly. Change them from 120 to 135.
# Display the updated sales array

In [68]:
import numpy as np
sales = np.array([
    [120,150,180],
    [100,130,160],
    [200,220,250]
])
print(sales[1])
print(sales[:,1])
sales = sales.astype(float)
sales[:,2]*=1.1
print(sales)
sales[0,0]=135
print(sales)

[100 130 160]
[150 130 220]
[[120. 150. 198.]
 [100. 130. 176.]
 [200. 220. 275.]]
[[135. 150. 198.]
 [100. 130. 176.]
 [200. 220. 275.]]


In [69]:
sales = np.array([
    [120,150,180],
    [100,130,160],
    [200,220,250]
])

In [ ]:
# display the complete sales data of branch 2

In [70]:
print(sales[1])

[100 130 160]


In [ ]:
# display the sales of all branches in february

In [71]:
print(sales[:,1])

[150 130 220]


In [ ]:
# Increase the March sales of every branch by 10%.
# a + 10%of a
# a + 0.1a
# a(1+0.1) = 1.1*a

In [72]:
sales[:,2] = sales[:,2]*1.1
print(sales[:,2])

[198 176 275]


In [ ]:
# The January sales of Branch 1 were entered incorrectly. Change them from 120 to 135.

In [73]:
sales[0,0] = 135

In [74]:
print(sales[0:0])

[]


In [75]:
print(sales)

[[135 150 198]
 [100 130 176]
 [200 220 275]]


In [ ]:
# An organization stores employee information as:
# Salary | Experience
# import numpy as np
# employees = np.array([
# [30000, 2],
# [40000, 4],
# [50000, 6],
# [60000, 8]
# ])
# Perform the following:
# Display the information of the last employee using negative indexing.
# Display the salary of the second employee.
# Increase the salary of the third employee by 15%.
# Add 1 year of experience to the first employee.
# Display the final employee array.

In [76]:
employees = np.array([
    [30000,2],
    [40000,4],
    [50000,6],
    [60000, 8]
])

In [ ]:
# display the information of the last employee using negative indexing .

In [77]:
employees[-1]

array([60000,     8])

In [ ]:
# display the salary of the second employee

In [78]:
employees[1,0]

np.int64(40000)

In [79]:
# Increase the salary of the third employee by 15%.
# a + 0.15*a = a(1+0.15) = 1.15*a

In [80]:
employees[2,0] = employees[2,0] + 0.15*employees[2,0]

In [ ]:
# employees[2,0] = employees[2,0]*1.15
# employees[2,0] *= 1.15

In [81]:
# Add 1 year of experience to the first employee.
employees[0,1] += 1


In [82]:
print(employees)

[[30000     3]
 [40000     4]
 [57500     6]
 [60000     8]]


In [ ]:
# A company has inventory information for 4 products across 3 warehouses.
# Columns: Warehouse A, Warehouse B, Warehouse C
# import numpy as np
# inventory = np.array([
# [100, 120, 150],
# [80, 90, 110],
# [200, 180, 160],
# [50, 70, 90]
# ])
# Perform the following:
# Display the inventory of Product 3 across all warehouses.
# Display the inventory of Warehouse B for all products.
# Warehouse A receives 20 additional units of every product. Update the array.
# The inventory of Product 4 in Warehouse C is incorrect. Change it to 100.
# Display the final inventory.

In [83]:
inventory=np.array([
    [100,120,150],
    [80,90,110],
    [200,180,160],
    [50,70,90]
])

In [ ]:
# display the inventory of product 3 across all warehouses .

In [84]:
print(inventory[2])

[200 180 160]


In [ ]:
# display the inventory of warehouse B for all products .

In [85]:
print(inventory[:,1])

[120  90 180  70]


In [ ]:
# the inventory of product 4 in warehouse c is incorrect . change it to 100 .

In [86]:
inventory[3,2] =100

In [87]:
print(inventory)

[[100 120 150]
 [ 80  90 110]
 [200 180 160]
 [ 50  70 100]]


In [ ]:
# A weather application stores temperatures for 3 cities.
# Columns: Morning, Afternoon, Evening
# import numpy as np
# temperature = np.array([
# [24, 35, 28],
# [22, 32, 26],
# [27, 38, 30]
# ])
# Perform the following:
# Display the complete temperature data of the first city.
# Display all afternoon temperatures.
# Display the evening temperature of the last city using negative indexing.
# Increase all morning temperatures by 2°C.
# The afternoon temperature of the second city was recorded incorrectly. Change it from 32 to 34.
# Display the final temperature array.

In [88]:
temperature = np.array([
    [24,35,28],
    [22,32,26],
    [27,38,30]
])

In [89]:
# Display the complete temperature data of the first city.
temperature[0]

array([24, 35, 28])

In [90]:
# Display all afternoon temperatures.
temperature[:,1]

array([35, 32, 38])

In [91]:
# Display the evening temperature of the last city using negative indexing.
temperature[-1,2]

np.int64(30)

In [92]:
temperature[-1,-1]

np.int64(30)

In [93]:
# inc all morning temperatures by 2 c .
temperature[:,0]+=2

In [94]:
# The afternoon temperature of the second city was recorded incorrectly. Change it from 32 to 34.
temperature[1,1] = 34

In [95]:
print(temperature)

[[26 35 28]
 [24 34 26]
 [29 38 30]]
