<a href="https://colab.research.google.com/github/anjalitiwarics27-coder/aiml/blob/main/4_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# A warehouse has 4 storage sections and 5 products.
# Initially, every product has a stock level of 100 units.
# Tasks
# Create a 4 × 5 array where every value is 100.
# Increase the stock of the first two sections by 20 units.
# Reduce stock of the last two products by 10%.
# Display only the middle two sections.
# Display only the first three products.
# Display the bottom-right 2 × 2 portion of the matrix .

In [2]:
import numpy as np
inventory = np.full((4,5),100)
print(inventory)

[[100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]]


In [3]:
inventory[::2,:] = inventory[:2,:] +20

In [4]:
# reduce stock of the last two products by 10%
inventory[:,-2:] = inventory[:,-2:]*0.90

In [5]:
# display only the middle two sections .
print(inventory[1:3,:])

[[100 100 100  90  90]
 [120 120 120 108 108]]


In [6]:
# Display only the first three products.
print(inventory[:,:3])

[[120 120 120]
 [100 100 100]
 [120 120 120]
 [100 100 100]]


In [7]:
inventory

array([[120, 120, 120, 108, 108],
       [100, 100, 100,  90,  90],
       [120, 120, 120, 108, 108],
       [100, 100, 100,  90,  90]])

In [8]:
# display the bottom - right 2*2 portion of the matrix .
inventory[-2:,-2:]

array([[108, 108],
       [ 90,  90]])

In [9]:
# A company has salary data for 4 employees:
# salary = np.array([
# [30000, 5000],
# [40000, 6000],
# [50000, 8000],
# [60000, 10000]
# ])
# Column 1 = Basic Salary
# Column 2 = Allowance
# Tasks
# Display the complete information of the 2nd employee.
# Display all basic salaries.
# Display all allowances.
# Increase all allowances by ₹1,000.
# Increase the basic salary of the last two employees by 10%.
# Display the final salary matrix.

In [10]:
salary = np.array([
    [30000,5000],
    [40000,6000],
    [50000,8000],
    [60000,10000]
])

In [11]:
# Display the complete information of the 2nd employee .
salary[1]

array([40000,  6000])

In [12]:
salary[1,:]

array([40000,  6000])

In [13]:
# display all basics salaries
salary[:,0]

array([30000, 40000, 50000, 60000])

In [14]:
# Display all allowances .
salary[:,1]

array([ 5000,  6000,  8000, 10000])

In [15]:
# Increase all allowance by $1,000
salary[-2:,0] +=1000

In [16]:
salary[:,1]*=1000

In [17]:
# salary[:,1] +=1000.5
salary[:,1] = salary[:,1]+1000.5

In [18]:
# Increase the basics salary of the last two employees by 10%

In [19]:
print(salary)

[[   30000  5001000]
 [   40000  6001000]
 [   51000  8001000]
 [   61000 10001000]]


In [20]:
# A startup expects its monthly users to grow from 10,000 to 100,000 over 12 months.
# Tasks
# Generate monthly user targets using np.linspace().
# Create month numbers using np.arange().
# Display users expected in Month 1 and Month 12.
# Display users expected from Months 4–8.
# Increase all targets by another 15%.
# Display the updated targets for the last 4 months.


In [21]:
# Genrate monthly user targets using np.linspace().
users = np.linspace(10000,100000,12)

In [22]:
print(users)

[ 10000.          18181.81818182  26363.63636364  34545.45454545
  42727.27272727  50909.09090909  59090.90909091  67272.72727273
  75454.54545455  83636.36363636  91818.18181818 100000.        ]


In [23]:
# Create month numbers using np.arange()

In [24]:
months = np.arange(1,13)

In [25]:
months

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [26]:
# Display users expected in month 1 and month 12 .
users[0]

np.float64(10000.0)

In [27]:
users[-1]

np.float64(100000.0)

In [28]:
# display users expected from month 4-8.
users[3:8]

array([34545.45454545, 42727.27272727, 50909.09090909, 59090.90909091,
       67272.72727273])

In [29]:
# increase  all targets by another 15%

In [30]:
users = users *1.15

In [31]:
print(users)

[ 11500.          20909.09090909  30318.18181818  39727.27272727
  49136.36363636  58545.45454545  67954.54545455  77363.63636364
  86772.72727273  96181.81818182 105590.90909091 115000.        ]


In [32]:
# display the updated targets for the last 4 months .
print(users[-4:])

[ 86772.72727273  96181.81818182 105590.90909091 115000.        ]


In [33]:
import numpy as np
numbers = np.array([4,9,16,25])

In [34]:
np.sqrt(numbers)

array([2., 3., 4., 5.])

In [35]:
np.sqrt(numbers)

array([2., 3., 4., 5.])

In [36]:
np.sqrt(49)

np.float64(7.0)

In [37]:
x= np.array([3,5,8])
y=np.array([4,12,15])
# distance from origin
distance = np.sqrt(x**2+y**2)

In [38]:
distance

array([ 5., 13., 17.])

In [39]:
x = np.array([3,5,8])
x**3

array([ 27, 125, 512])

In [40]:
a = np.power(x,3)

In [41]:
print(a)

[ 27 125 512]


In [42]:
np.cbrt(a)

array([3., 5., 8.])

In [43]:
a**(1/3)

array([3., 5., 8.])

In [44]:
numbers = np.array([-10,-5,0,5,10])
np.abs(numbers)

array([10,  5,  0,  5, 10])

In [45]:
n= len(numbers)
for i in range(n):
  if numbers[i]<0:
    numbers[i]*=-1
print(numbers)

[10  5  0  5 10]


In [46]:
np.sqrt(np.square(numbers))

array([10.,  5.,  0.,  5., 10.])

In [47]:
values =np.array([10.2345,20.6789,30.4567])
np.around(values)

array([10., 21., 30.])

In [48]:
values =np.array([10.2345,20.6789,30.4567])
np.around(values,2)

array([10.23, 20.68, 30.46])

In [49]:
values = np.array([2.1,2.9,5.5,7.99])
# round down
np.floor(values)

array([2., 2., 5., 7.])

In [50]:
values = np.array([2.9,5.7,-3.8,-7.2])
np.trunc(values)

array([ 2.,  5., -3., -7.])

In [51]:
# An e-commerce company stores order informations :
# orders = np.array([
# [1000, 2, 500],
# [1001, 3, 750],
# [1002, 1, 1200],
# [1003, 4, 300],
# [1004, 2, 900]
# ])
# Columns:
# Column 1 → Order ID
# Column 2 → Quantity
# Column 3 → Price per item
# Tasks
# Display the complete information of Order 1002.
# Display all quantities.
# Display all prices.
# Display the first 3 orders.
# Display the last 2 orders.
# Increase the price of the last 2 products by 10%.
# Increase the quantity of the first order by 1.
# Display the final dataset.
# Create a separate array containing only the quantity and price columns.
# Display the shape and size of the dataset.

In [52]:
orders=np.array([
    [1000,2,500],
    [1001,3,750],
    [1002,1,1200],
    [1003,4,300],
    [1004,2,900]
])

In [53]:
# display the complete information of order 1002 .
orders[2]

array([1002,    1, 1200])

In [54]:
# display all quantities
orders[:,1]

array([2, 3, 1, 4, 2])

In [55]:
orders[:,2]

array([ 500,  750, 1200,  300,  900])

In [56]:
# display the first 3 orders .
orders[:3]

array([[1000,    2,  500],
       [1001,    3,  750],
       [1002,    1, 1200]])

In [57]:
# display the last 2 orders .
orders[-2:]

array([[1003,    4,  300],
       [1004,    2,  900]])

In [58]:
# increase the price of the last 2 prducts by 10%
orders[-2:,-1] = orders[-2:,-1]*1.10
print(orders[-2:,-1])

[330 990]


In [59]:
# Increase the prices of the last 2 products by 10%
orders[-2:,-1] = orders[-2:,-1]*1.1
print(orders[-2:,-1])

[ 363 1089]


In [60]:
#increase the quantity of the first order by 1 .
orders[0,1]+=1

In [62]:
print(orders)

[[1000    3  500]
 [1001    3  750]
 [1002    1 1200]
 [1003    4  363]
 [1004    2 1089]]


In [ ]:
# Create a separate array containing only the quantity and price columns .

In [65]:
quantity_price=orders[:,1:3]

In [66]:
quantity_price

array([[   3,  500],
       [   3,  750],
       [   1, 1200],
       [   4,  363],
       [   2, 1089]])

In [67]:
orders.shape

(5, 3)

In [68]:
orders.size

15

##HW

In [69]:
# A simple grayscale image can be represented as a 2D NumPy array where each number represents pixel intensity.
# image = np.array([
# [10, 20, 30, 40, 50],
# [20, 30, 40, 50, 60],
# [30, 40, 50, 60, 70],
# [40, 50, 60, 70, 80],
# [50, 60, 70, 80, 90]
# ])
# Tasks
# Find the dimensions of the image.
# Find its shape.
# Find the total number of pixels.
# Display the center pixel.
# Extract the top-left 3 × 3 region.
# Extract the bottom-right 2 × 2 region.
# Increase the intensity of the center 3 × 3 region by 20.
# Display the modified image.

In [77]:
import numpy as np

# Define the image array
image = np.array([
    [10, 20, 30, 40, 50],
    [20, 30, 40, 50, 60],
    [30, 40, 50, 60, 70],
    [40, 50, 60, 70, 80],
    [50, 60, 70, 80, 90]
])

# 1. Dimensions of the image
dimensions = image.ndim
print("Dimensions:", dimensions)

# 2. Shape of the image
shape = image.shape
print("Shape:", shape)

# 3. Total number of pixels
total_pixels = image.size
print("Total number of pixels:", total_pixels)

# 4. Center pixel
center_pixel = image[2, 2]
print("Center pixel:", center_pixel)

# 5. Extract top-left 3 x 3 region
top_left_3x3 = image[:3, :3]
print("Top-left 3x3 region:\n", top_left_3x3)

# 6. Extract bottom-right 2 x 2 region
bottom_right_2x2 = image[-2:, -2:]
print("Bottom-right 2x2 region:\n", bottom_right_2x2)

# 7. Increase intensity of center 3 x 3 region by 20
image[1:4, 1:4] += 20

# 8. Display modified image
print("Modified image:\n", image)

Dimensions: 2
Shape: (5, 5)
Total number of pixels: 25
Center pixel: 50
Top-left 3x3 region:
 [[10 20 30]
 [20 30 40]
 [30 40 50]]
Bottom-right 2x2 region:
 [[70 80]
 [80 90]]
Modified image:
 [[10 20 30 40 50]
 [20 50 60 70 60]
 [30 60 70 80 70]
 [40 70 80 90 80]
 [50 60 70 80 90]]


In [70]:
import numpy as np
image=np.array([
    [10,20,30,40,50],
    [20,30,40,50,60],
    [30,40,50,60,70],
    [40,50,60,70,80],
    [50,60,70,80,90]
])

In [71]:
image.ndim

2

In [72]:
image.shape

(5, 5)

In [75]:
image.size

25

In [76]:
image[2,2]

np.int64(50)

In [78]:
image[:3,:3]

array([[10, 20, 30],
       [20, 50, 60],
       [30, 60, 70]])

In [79]:
image[-2:,-2:]

array([[90, 80],
       [80, 90]])

In [81]:
image[1:4,1:4]+=20
print(image)

[[ 10  20  30  40  50]
 [ 20  90 100 110  60]
 [ 30 100 110 120  70]
 [ 40 110 120 130  80]
 [ 50  60  70  80  90]]


In [ ]:
# A company stores quarterly revenue and expenses:
# financials = np.array([
# [120, 80],
# [150, 90],
# [180, 110],
# [200, 130]
# ])
# Rows = Q1, Q2, Q3, Q4
# Columns = Revenue, Expense
# Tasks
# Display Q2's complete financial data.
# Display all quarterly revenues.
# Display all quarterly expenses.
# Extract Q2 and Q3 data.
# Increase Q4 revenue by 15%.
# Reduce Q1 expense by 10%.
# Display the final financial matrix.

In [82]:
import numpy as np

# Initial financial matrix
financials = np.array([
    [120, 80],   # Q1
    [150, 90],   # Q2
    [180, 110],  # Q3
    [200, 130]   # Q4
])

# 1. Display Q2's complete financial data
print("Q2 Data:", financials[1])

# 2. Display all quarterly revenues (Column 0)
print("Revenues:", financials[:, 0])

# 3. Display all quarterly expenses (Column 1)
print("Expenses:", financials[:, 1])

# 4. Extract Q2 and Q3 data
print("Q2 and Q3 Data:\n", financials[1:3])

# 5. Increase Q4 revenue by 15%
financials[3, 0] = financials[3, 0] * 1.15

# 6. Reduce Q1 expense by 10%
financials[0, 1] = financials[0, 1] * 0.90

# 7. Display the final financial matrix
print("\nFinal Financial Matrix:\n", financials)

Q2 Data: [150  90]
Revenues: [120 150 180 200]
Expenses: [ 80  90 110 130]
Q2 and Q3 Data:
 [[150  90]
 [180 110]]

Final Financial Matrix:
 [[120  72]
 [150  90]
 [180 110]
 [229 130]]


In [ ]:
# A classroom has 6 rows and 5 seats per row.
# Initially, all seats are empty.
# 0 = Empty
# 1 = Occupied
# Tasks
# Create a 6 × 5 array filled with zeros.
# Mark the first seat of the first row as occupied.
# Mark all seats in the 3rd row as occupied.
# Mark the last two seats of the last row as occupied.
# Display the first 3 rows.
# Display the last 2 columns.
# Display the complete seating matrix .

In [83]:
import numpy as np

# 1. Create a 6 x 5 array filled with zeros
seating = np.zeros((6, 5), dtype=int)

# 2. Mark the first seat of the first row as occupied
seating[0, 0] = 1

# 3. Mark all seats in the 3rd row as occupied (row index 2)
seating[2, :] = 1

# 4. Mark the last two seats of the last row as occupied
seating[-1, -2:] = 1

# 5. Display the first 3 rows
print("First 3 rows:\n", seating[:3])

# 6. Display the last 2 columns
print("\nLast 2 columns:\n", seating[:, -2:])

# 7. Display the complete seating matrix
print("\nComplete Seating Matrix:\n", seating)

First 3 rows:
 [[1 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 1 1]]

Last 2 columns:
 [[0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]]

Complete Seating Matrix:
 [[1 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 1 1]]
