<a href="https://colab.research.google.com/github/anjalitiwarics27-coder/aiml/blob/main/4_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# A simple grayscale image can be represented as a 2D NumPy array where each number represents pixel intensity.
# image = np.array([
# [10, 20, 30, 40, 50],
# [20, 30, 40, 50, 60],
# [30, 40, 50, 60, 70],
# [40, 50, 60, 70, 80],
# [50, 60, 70, 80, 90]
# ])
# Tasks
# Find the dimensions of the image.
# Find its shape.
# Find the total number of pixels.
# Display the center pixel.
# Extract the top-left 3 × 3 region.
# Extract the bottom-right 2 × 2 region.
# Increase the intensity of the center 3 × 3 region by 20.
# Display the modified image.

In [1]:
import numpy as np
image=np.array([
    [10,20,30,40,50],
    [20, 30, 40, 50, 60],
    [30, 40, 50, 60, 70],
    [40, 50, 60, 70, 80],
    [50, 60, 70, 80, 90]
])

In [2]:
image.ndim

2

In [3]:
image.shape

(5, 5)

In [4]:
image.size

25

In [5]:
image[2,2]

np.int64(50)

In [6]:
image[:3,:3]

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

In [7]:
image[-2:,-2:]

array([[70, 80],
       [80, 90]])

In [8]:
image

array([[10, 20, 30, 40, 50],
       [20, 30, 40, 50, 60],
       [30, 40, 50, 60, 70],
       [40, 50, 60, 70, 80],
       [50, 60, 70, 80, 90]])

In [ ]:
#inc the intensity of the center 3 * 3 region by 20 .

In [9]:
image[1:4,1:4]+=20

In [10]:
image[1:4,1:4]

array([[50, 60, 70],
       [60, 70, 80],
       [70, 80, 90]])

In [12]:
print(image)

[[10 20 30 40 50]
 [20 50 60 70 60]
 [30 60 70 80 70]
 [40 70 80 90 80]
 [50 60 70 80 90]]


In [ ]:
# A company stores quarterly revenue and expenses:
# financials = np.array([
# [120, 80],
# [150, 90],
# [180, 110],
# [200, 130]
# ])
# Rows = Q1, Q2, Q3, Q4
# Columns = Revenue, Expense
# Tasks
# Display Q2's complete financial data.
# Display all quarterly revenues.
# Display all quarterly expenses.
# Extract Q2 and Q3 data.
# Increase Q4 revenue by 15%.
# Reduce Q1 expense by 10%.
# Display the final financial matrix.

In [13]:
import numpy as np
financials=np.array([
    [120,80],
    [150,90],
    [180,110],
    [200,130]
])

In [14]:
# display Q2 ' s complete financial data .
financials[1]

array([150,  90])

In [15]:
# display all quarterly revenues .
financials[:,0]

array([120, 150, 180, 200])

In [16]:
# display all quarterly expenses .
financials[:,1]

array([ 80,  90, 110, 130])

In [17]:
financials[:,-1]

array([ 80,  90, 110, 130])

In [18]:
#Extract q2 and q3 data .
financials[1:3,]

array([[150,  90],
       [180, 110]])

In [19]:
# Increase q4 revenue by 15 %
financials[3,0] = financials[3,0]*1.15
print(financials)

[[120  80]
 [150  90]
 [180 110]
 [229 130]]


In [20]:
# Reduce q1 expense by 10 %
financials[0,1] = financials[0,1]*0.9
print(financials)

[[120  72]
 [150  90]
 [180 110]
 [229 130]]


In [ ]:
# A classroom has 6 rows and 5 seats per row
# Initially, all seats are empty.
# 0 = Empty
# 1 = Occupied
# Tasks
# Create a 6 × 5 array filled with zeros.
# Mark the first seat of the first row as occupied.
# Mark all seats in the 3rd row as occupied.
# Mark the last two seats of the last row as occupied.
# Display the first 3 rows.
# Display the last 2 columns.
# Display the complete seating matrix.

In [21]:
# Create a 6 * 5 arrays filled with zeros .
seat = np.full((6,5),0)
seat

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [22]:
# Mark the first seat of the first row as occupied .
seat[0,0]=1
seat

array([[1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [23]:
# Mark all seat in the 3rd row as occupied
seat[2]=1
seat

array([[1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [24]:
# Mark the last two seats of the last row as occupied
seat[5,-2:] = 1
seat

array([[1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1]])

In [25]:
# display the first 3 rows .
seat[:3]

array([[1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1]])

In [26]:
# display the last 2 columns
seat [:,-2:]

array([[0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1]])

In [27]:
seat

array([[1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1]])

In [28]:
sales = np.array([100,200,300,400,500])
sales

array([100, 200, 300, 400, 500])

In [29]:
sm = 0
for elem in sales :
  sm +=elem
print(sm)

1500


In [30]:
sm =0
n=len(sales)
for elem in sales :
  sm+=elem
print(sm/n)

300.0


In [31]:
np.sum(sales)

np.int64(1500)

In [32]:
np.avg(sales)

AttributeError: module 'numpy' has no attribute 'avg'

In [33]:
np.mean(sales)

np.float64(300.0)

In [34]:
# fine the min salary
sales = np.array([100,200,300,400,500])
mn = 0
for s in sales :
  if s<mn:
    mn=s
print(mn)

0


In [ ]:
#fine the min salary

In [35]:
sales = np.array([100,200,300,400,500])
mx= 0
for s in sales:
  if s>mx :
    mx= s
print(mx)

500


In [ ]:
# fine the max salary

In [36]:
sales =np.array([-100,-200,-300,-400,-500])
mx = 0
for s in sales :
  if s>mx:
    mx = s
print(mx )

0


In [37]:
# fine the max salary
sales = np.array([-100,-200,-300,-400,-500])
mx = sales [0]
for s in sales :
  if s>mx:
    mx=s
print(mx)

-100


In [40]:
## fine the max salary
import numpy as np
sales = np.array([-100,-200,-300,-400,-500])
mx = sales [2]
for s in sales :
  if s>mx:
    mx=s
print(mx)

-100


In [41]:
sales = np.array([100,200,300,400,500])
np.min(sales)

np.int64(100)

In [42]:
np.max(sales)

np.int64(500)

In [43]:
sales = np.array([50,30,10,190,100])
# median?

In [ ]:
# A teacher has recorded marks of 10 students:
# marks = np.array([72, 85, 91, 64, 78, 88, 95, 70, 82, 76])
# Find:
# Total marks
# Average marks
# Highest marks
# Lowest marks
# Difference between highest and lowest marks
# Index of the student with the highest marks

In [44]:
marks = np.array([72, 85, 91, 64, 78, 88, 95, 70, 82, 76])
total=np.sum(marks)
total

np.int64(801)

In [45]:
avg = np.mean(marks)
avg

np.float64(80.1)

In [46]:
np.min(marks)

np.int64(64)

In [47]:
np.max(marks)

np.int64(95)

In [48]:
np.max(marks)-np.min(marks)

np.int64(31)

In [49]:
marks

array([72, 85, 91, 64, 78, 88, 95, 70, 82, 76])

In [50]:
mx = marks[0]
mxi = 0
n = len(marks)
for i in range(n):
  if mx<marks[i]:
    mx= marks[i]
    mxi = i
print(mx,mxi)

95 6


In [51]:
np.argmax(marks)

np.int64(6)

In [53]:
marks = np.array([72, 85, 91, 64, 78, 88, 95, 70, 82, 76])
np.argmax(marks)

np.int64(6)

In [ ]:
# A company's daily sales for 7 days are:
# sales = np.array([45000, 47000, 49000, 52000, 50000, 48000, 250000])
# Calculate the mean and median.
# Then determine which measure better represents a typical sales day when considering the unusually large sale.
# Also calculate the standard deviation.

In [54]:
sales = np.array([45000, 47000, 49000, 52000, 50000, 48000, 250000])
np.mean(sales)

np.float64(77285.71428571429)

In [55]:
np.median(sales)

np.float64(49000.0)

In [56]:
np.std(sales)

np.float64(70540.18973143565)

In [ ]:
# A business records revenue for 12 months:
# revenue = np.array([
# 120000, 135000, 128000, 145000,
# 150000, 138000, 160000, 172000,
# 155000, 148000, 180000, 195000
# ])
# Find:
# Average monthly revenue
# Highest revenue
# Lowest revenue
# Month index with highest revenue
# Month index with lowest revenue
# Total annual revenue
# Difference between highest and lowest revenue .

In [ ]:
# # The following array contains sales made by 4 salespeople across 3 months.
# # sales = np.array([
# # [120, 150, 180],
# # [200, 170, 160],
# # [100, 140, 130],
# # [180, 190, 210]
# # ])
# # Rows represent salespeople and columns represent months.
# Find:
# Total sales by each salesperson
# Average sales by each salesperson
# Total sales for each month
# Average sales for each month
# Highest sales achieved by each salesperson