<a href="https://colab.research.google.com/github/anjalitiwarics27-coder/aiml/blob/main/4_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
marks = np.array([70,80,65,90,75])
print(np.sum(marks))
print(np.mean(marks))
print(np.min(marks))
print(np.max(marks))
print(np.std(marks))
print(np.var(marks))

380
76.0
65
90
8.602325267042627
74.0


In [5]:
80>70

True

In [6]:
(80<90) and(20>30)

False

False

In [7]:
(80<90) or(20>30)

True

In [8]:
80==80

True

In [10]:
80 !=80

False

In [11]:
marks = np.array([70,80,65,90,75])
marks>75

array([False,  True, False,  True, False])

In [ ]:
# Write a code to filter in only the marks >75 .

In [12]:
a=[70,80,65,90,75]
marks>75

array([False,  True, False,  True, False])

In [ ]:
# write a code to filter in only the marks >75 .

In [13]:
a= [70,80,65,90,75]
b=[]
for elem in a :
  if elem>75:
    b.append(elem)
print(b)

[80, 90]


In [14]:
marks

array([70, 80, 65, 90, 75])

In [16]:
marks[[False,True,False,True,False]]

array([80, 90])

In [17]:
marks[marks>75]

array([80, 90])

In [18]:
temperature = np.array([
    24,28,31,35,29,22,37,30
])
# temp atleast 32
temperature[ temperature >= 32]

array([35, 37])

In [19]:
prices = np.array([
    499,799,1299,2499,3999,599
])
# prices between 600 and 1000
prices[(prices >= 600) and (prices <= 1000)]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [20]:
prices>=600

array([False,  True,  True,  True,  True, False])

In [21]:
prices<=1000

array([ True,  True, False, False, False,  True])

In [22]:
prices[(prices>=600)&(prices<=1000)]

array([799])

In [23]:
# prices less than 600 or greater than 1000
prices[(prices<600) or(prices>1000)]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [24]:
prices[(prices<600)|(prices>1000)]

array([ 499, 1299, 2499, 3999,  599])

In [25]:
# show prices not greater than 900
prices<=900

array([ True,  True, False, False, False,  True])

In [26]:
prices[not(prices>900)]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [27]:
prices[~(prices>900)]

array([499, 799, 599])

In [28]:
marks= np.array([
    [72,85,90],
    [55,60,65],
    [88,92,95],
    [45,50,48]
])

In [29]:
# filter marks >70
marks[marks>70]

array([72, 85, 90, 88, 92, 95])

In [31]:
sales = np.array([
    [100,200,300],
    [400,500,600],
    [150,250,350]
])
# find valus greater than 200 only in the first row :
sales[0,sales[0]>200]
# sales [sales[0]>200]

array([300])

In [32]:
products = np.array([
    [101,500],
    [102,1200],
    [103,800],
    [104,1500]
])

In [35]:
# we want products prices whoes prices is greater than $ 1,000
prices = products[:,1]

In [36]:
prices

array([ 500, 1200,  800, 1500])

In [37]:
prices[prices>1000]

array([1200, 1500])

##TEST DPP

In [40]:
# An electricity board records the montly electricity consumption of a household for one year:
consumption = np.array([
180, 220, 195, 250,
280, 310, 295, 270,
240, 210, 190, 230
])
# Perform the following:
# Find the total annual consumption.
# Calculate average monthly consumption.
# Find the highest and lowest consumption.
# Find the month index with the highest consumption.
# Extract the first 6 months using slicing.
# Extract alternate months.
# Find all months where consumption was greater than the annual average.
# Calculate the new monthly projections if next year's consumption is expected to be 8% higher.

In [41]:
c = np.array([
    180,270,195,250,280,310,295,270,240,210,190,230
])

In [42]:
# find the total annual consumptions .
np.sum(c)

np.int64(2920)

In [43]:
# calculate average montly consumption .
np.mean(c)

np.float64(243.33333333333334)

In [44]:
# find the highest and lowest consumption .
np.min(c)

np.int64(180)

In [45]:
np.max(c)

np.int64(310)

In [47]:
# find the month index with the highest consumption .
np.argmax(c)

np.int64(5)

In [48]:
# Extract the first 6 months using slicing .
c[:6]

array([180, 270, 195, 250, 280, 310])

In [49]:
# extract alternate months
c[::2]

array([180, 195, 280, 295, 240, 190])

In [50]:
np.mean(c)

np.float64(243.33333333333334)

In [51]:
# find all months where consumptions was greater than the annual average .
c[c>np.mean(c)]

array([270, 250, 280, 310, 295, 270])

In [52]:
c


array([180, 270, 195, 250, 280, 310, 295, 270, 240, 210, 190, 230])

In [53]:
# calculate the new montly projections if next year's consumption is expected to be 8% higher .


In [54]:
next = c*1.08

In [55]:
next

array([194.4, 291.6, 210.6, 270. , 302.4, 334.8, 318.6, 291.6, 259.2,
       226.8, 205.2, 248.4])

In [ ]:
# problem statement
# The following array contains marks of 5 students in 4 subjects:
# marks = np.array([
# [72, 85, 90, 78],
# [65, 70, 75, 80],
# [88, 92, 95, 90],
# [55, 60, 58, 65],
# [78, 82, 85, 88]
# ])
# Assume each row represents a student and each column represents a subject.
# Find:
# Shape and size of the array.
# Marks obtained by the third student.
# Marks obtained in the second subject by all students.
# Average marks of every student.
# Average marks of every subject.
# Students whose average is above 75.
# Highest mark obtained in each subject.
# The complete row of the student with the highest average

In [56]:
marks= np.array([
    [72,85,90,78],
    [65,70,75,80],
    [88,92,95,90],
    [55,60,58,65],
    [78,82,85,88]
])


In [57]:
# shape and size of the array .
marks.shape

(5, 4)

In [58]:
marks.size

20

In [59]:
# marks obtained by the third students

In [60]:
marks[2]

array([88, 92, 95, 90])

In [61]:
# marks obtained by the third students .
marks[2]

array([88, 92, 95, 90])

In [62]:
# marks obtained in the second subject by all students .
marks[:,1]

array([85, 70, 92, 60, 82])

In [63]:
# Average marks of every student .
np.mean(marks,axis=1)

array([81.25, 72.5 , 91.25, 59.5 , 83.25])

In [64]:
# Average marks of every students .
np.mean(marks,axis=1)

array([81.25, 72.5 , 91.25, 59.5 , 83.25])

In [66]:
array= np.array([81.25,72.5,91.25,59.5,83.25])

In [67]:
# Average marks of every subject .
np.mean(marks,axis=0)

array([71.6, 77.8, 80.6, 80.2])

In [68]:
# Students whose average is above 75 .
marks

array([[72, 85, 90, 78],
       [65, 70, 75, 80],
       [88, 92, 95, 90],
       [55, 60, 58, 65],
       [78, 82, 85, 88]])

In [69]:
std_avg = np.mean(marks,axis=1)

In [70]:
marks[std_avg>75]

array([[72, 85, 90, 78],
       [88, 92, 95, 90],
       [78, 82, 85, 88]])

In [71]:
# Highest mark obtained in each subject.
np.max(marks,axis=0)

array([88, 92, 95, 90])

In [72]:
# The complete row of the student with the highest average
ind = np.argmax(std_avg)

In [73]:
ind

np.int64(2)

In [74]:
marks[ind]

array([88, 92, 95, 90])

In [77]:
# An online store has the following product prices:
prices = np.array([
499.50, 799.90, 1299.75,
2499.50, 3999.90, 599.25,
899.80, 1599.40
])
# Perform:
# Round prices to the nearest whole number.
# Find products costing more than ₹1,000.
# Calculate a 15% discount only on products costing more than ₹1,000.
# Calculate the average discounted price of those products.
# Find the most expensive original product.
# Extract the last 4 products.
# Calculate the square root of the final prices and round them to 2 decimal places.

In [78]:
# Round prices to the nearest whole number .
np.round(prices)

array([ 500.,  800., 1300., 2500., 4000.,  599.,  900., 1599.])

In [ ]:
# Find products costing more tha $ 1,000

In [79]:
prices[prices>1000]

array([1299.75, 2499.5 , 3999.9 , 1599.4 ])

In [80]:
# Calculate a 15% discount only on product costing more than $ 1000.
discounted = np.round(prices[prices>1000]*0.85)

In [81]:
# Calculated the average discounted prices of those products .
np.mean(discounted)

np.float64(1997.25)

In [82]:
# Find the most expensive original product .
np.max(prices)

np.float64(3999.9)

In [83]:
np.argmax(prices)

np.int64(4)

In [84]:
# Calculate the square root of the final prices and round them to 2 decimal places .
sqrt_prices = np.sqrt(discounted)
final=np.round(sqrt_prices,2)

In [85]:
final

array([33.24, 46.1 , 58.31, 36.86])